# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jasmo2github
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: gettingstarted
# "service" is the name of this project. This will also be added to your AWS resource names.
service: jaime

provider:
  name: aws
  runtime: nodejs20.x
  region: 'us-east-1'
  iamRoleStatements:
    - Effect: Allow
      Action:
          - dynamodb:*
      Resource:
          - arn:aws:dynamodb:us-east-1:xxxxxxxxxxxx:table/MoviesTable

resources:
  Resources:
    MoviesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MoviesTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
        - AttributeName: id
          KeyType: HASH

functions:
  api:
    handler: handler.hello
    events:
      - httpApi: 
          path: /
          method: get
  createMovie:
    handler: movies/createMovie.createMovie
    events:
      - httpApi:
          path: /movies
          method: post
